[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/work"
  to = "/work.html"
  status = 200

[[redirects]]
  from = "/consultation"
  to = "/consultation.html"
  status = 200

[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

[[redirects]]
  from = "/review"
  to = "/review.html"
  status = 200
